version: '3.1'

services:
  app-tch:
    build: .
    restart: always
    ports:
      - "8001:8000"
    environment:
      - SITE=TCH
  app-methodist:
    build: .
    restart: always
    ports:
      - "8002:8000"
    environment:
      - SITE=METHODIST
  app-bslmc:
    build: .
    restart: always
    ports:
      - "8003:8000"
    environment:
      - SITE=BSLMC
  app-harrishealth:
    build: .
    restart: always
    ports:
      - "8004:8000"
    environment:
      - SITE=HarrisHealth
