version: '3.1'

services:
  app-bcm:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SITE=BCM
  app-methodist:
    build: .
    restart: always
    ports:
      - "8001:8000"
    environment:
      - SITE=METHODIST
  app-bslmc:
    build: .
    restart: always
    ports:
      - "8002:8000"
    environment:
      - SITE=BSLMC
  app-harrishealth:
    build: .
    restart: always
    ports:
      - "8003:8000"
    environment:
      - SITE=HarrisHealth
