#!/usr/bin/env bash

# script/server: Launch the application and any extra required processes
#                locally.

set -e
cd "$(dirname "$0")/.."

echo
#echo "==> Loading .env…"
#set -o allexport; source .env; set +o allexport

echo
echo "==> Starting containers with docker-compose…"
docker-compose up -d --build